In [1]:
wikiLink="https://es.wikipedia.org/wiki/Anexo:Pel%C3%ADculas_con_las_mayores_recaudaciones"

In [2]:
import html5lib

In [3]:
import pandas as pd

tablas=pd.read_html(wikiLink)

In [4]:
type(tablas)

list

In [5]:
pelTaquilla=tablas[0].copy()

In [6]:
pelTaquilla

,N.º,Película,Distribuidora (s),Taquilla (Estados Unidos),Taquilla (fuera de EE UU ),Recaudación mundial,Presupuesto,Año de estreno,Director (es)
0,1,Avatar,20th Century Fox,"$785 221 649 (26,9%)","$2 138 484 377 (73,1%)",$2 923 706 026,$237 000 000,2009,James Cameron
1,2,Avengers: Endgame,Walt Disney Studios Motion Pictures,"$858 373 000 (30,7%)","$1 941 066 100 (69,3%)",$2 799 439 100,$356 000 000,2019,Anthony y Joe Russo
2,3,Avatar: The Way of Water,Walt Disney Studios Motion Pictures,"$683 196 773 (29,5%)","$1 633 765 357 (70,5%)",$2 316 962 130,$350 000 000-460 000 000,2022,James Cameron
3,4,Titanic,20th Century Fox / Paramount Pictures,"$674 292 608 (29,8%)","$1 588 998 952 (70,2%)",$2 263 291 560,$200 000 000,1997,James Cameron
4,5,Star Wars: Episodio VII - El despertar de la F...,Walt Disney Studios Motion Pictures,"$936 662 225 (45,2%)","$1 134 647 993 (54,8%)",$2 071 310 218,$306 000 000,2015,J. J. Abrams
...,...,...,...,...,...,...,...,...,...
95,96,Shrek The Third,Paramount Pictures,"$322 719 944 (39,7%)","$490 647 436 (60,3%)",$813 367 380,$160 000 000,2007,Chris Miller
96,97,Coco,Walt Disney Studios Motion Pictures,$210 460 015 (26%),$597 357 873 (74%),$807 817 888,$175 000 000,2017,Lee Unkrich/ Adrian Molina
97,98,Jumanji: The Next Level,Sony Pictures Releasing,$320 314 960 (40%),$481 378 969 (60%),$801 693 929,$125 000 000,2019,Jake Kasdan
98,99,Harry Potter y el prisionero de Azkaban,Warner Bros. Pictures,"$250 105 651 (31,4%)","$547 555 114 (68,6%)",$797 660 766,$130 000 000,2004,Alfonso Cuarón
99,100,Piratas del Caribe: La venganza de Salazar,Walt Disney Studios Motion Pictures,"$172 558 876 (21,7%)","$623 363 422 (78,3%)",$795 922 298,$230 000 000,2017,Joachim Ronning / Espen Sandberg

In [7]:
#El tipo de información que proporciona la tabla
pelTaquilla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   N.º                         100 non-null    int64
 1   Película                    100 non-null    object
 2   Distribuidora (s)           100 non-null    object
 3   Taquilla (Estados Unidos)   100 non-null    object
 4   Taquilla (fuera de EE UU )  100 non-null    object
 5   Recaudación mundial         100 non-null    object
 6   Presupuesto                 100 non-null    object
 7   Año de estreno              100 non-null    int64
 8   Director (es)               100 non-null    object
dtypes: int64(2), object(7)
memory usage: 7.2+ KB

In [8]:
#Nombre real de las columnas de la tabla
pelTaquilla.columns.to_list()

['N.º',
 'Película',
 'Distribuidora (s)',
 'Taquilla (Estados Unidos)',
 'Taquilla (fuera de EE UU\xa0)',
 'Recaudación mundial',
 'Presupuesto',
 'Año de estreno',
 'Director (es)']

In [9]:
#Eliminando los espacios de los nombres de las columnas para poder configurarlos fácilmente
pelTaquilla.columns=pelTaquilla.columns.str.replace(' ', '')

In [10]:
#Nombre real actual de las columnas de la tabla
pelTaquilla.columns.to_list()

['N.º',
 'Película',
 'Distribuidora(s)',
 'Taquilla(EstadosUnidos)',
 'Taquilla(fueradeEEUU\xa0)',
 'Recaudaciónmundial',
 'Presupuesto',
 'Añodeestreno',
 'Director(es)']

In [11]:
#Reemplazo el nombre de N. Unidos por "ranking" para mayor rapidez al configurarlo
pelTaquilla.rename(columns = {'N.º':'ranking'}, inplace = True)

In [12]:
#Reemplazo el nombre de la taquilla fuera de Estados Unidos por "ta_NO_USA" para mayor rapidez al configurarlo
#Notamos que "\xa0" representa un espacio que no se observa a simple vista en la tabla
pelTaquilla.rename(columns = {'Taquilla(fueradeEEUU\xa0)':'ta_NO_USA'}, inplace = True)

In [13]:
#Reemplazo el nombre de la taquilla en Estados Unidos por "ta_USA" para mayor rapidez al configurarlo
pelTaquilla.rename(columns = {'Taquilla(EstadosUnidos)':'ta_USA'}, inplace = True)

In [14]:
pelTaquilla

,ranking,Película,Distribuidora(s),ta_USA,ta_NO_USA,Recaudaciónmundial,Presupuesto,Añodeestreno,Director(es)
0,1,Avatar,20th Century Fox,"$785 221 649 (26,9%)","$2 138 484 377 (73,1%)",$2 923 706 026,$237 000 000,2009,James Cameron
1,2,Avengers: Endgame,Walt Disney Studios Motion Pictures,"$858 373 000 (30,7%)","$1 941 066 100 (69,3%)",$2 799 439 100,$356 000 000,2019,Anthony y Joe Russo
2,3,Avatar: The Way of Water,Walt Disney Studios Motion Pictures,"$683 196 773 (29,5%)","$1 633 765 357 (70,5%)",$2 316 962 130,$350 000 000-460 000 000,2022,James Cameron
3,4,Titanic,20th Century Fox / Paramount Pictures,"$674 292 608 (29,8%)","$1 588 998 952 (70,2%)",$2 263 291 560,$200 000 000,1997,James Cameron
4,5,Star Wars: Episodio VII - El despertar de la F...,Walt Disney Studios Motion Pictures,"$936 662 225 (45,2%)","$1 134 647 993 (54,8%)",$2 071 310 218,$306 000 000,2015,J. J. Abrams
...,...,...,...,...,...,...,...,...,...
95,96,Shrek The Third,Paramount Pictures,"$322 719 944 (39,7%)","$490 647 436 (60,3%)",$813 367 380,$160 000 000,2007,Chris Miller
96,97,Coco,Walt Disney Studios Motion Pictures,$210 460 015 (26%),$597 357 873 (74%),$807 817 888,$175 000 000,2017,Lee Unkrich/ Adrian Molina
97,98,Jumanji: The Next Level,Sony Pictures Releasing,$320 314 960 (40%),$481 378 969 (60%),$801 693 929,$125 000 000,2019,Jake Kasdan
98,99,Harry Potter y el prisionero de Azkaban,Warner Bros. Pictures,"$250 105 651 (31,4%)","$547 555 114 (68,6%)",$797 660 766,$130 000 000,2004,Alfonso Cuarón
99,100,Piratas del Caribe: La venganza de Salazar,Walt Disney Studios Motion Pictures,"$172 558 876 (21,7%)","$623 363 422 (78,3%)",$795 922 298,$230 000 000,2017,Joachim Ronning / Espen Sandberg

In [15]:
#Elimino ranking,ta_NO_USA,ta_USA usando "drop"
byeColumns=['ta_USA','ranking','ta_NO_USA']

#El resultado
pelTaquilla.drop(columns=byeColumns,inplace=True)
#Ahora
pelTaquilla

,Película,Distribuidora(s),Recaudaciónmundial,Presupuesto,Añodeestreno,Director(es)
0,Avatar,20th Century Fox,$2 923 706 026,$237 000 000,2009,James Cameron
1,Avengers: Endgame,Walt Disney Studios Motion Pictures,$2 799 439 100,$356 000 000,2019,Anthony y Joe Russo
2,Avatar: The Way of Water,Walt Disney Studios Motion Pictures,$2 316 962 130,$350 000 000-460 000 000,2022,James Cameron
3,Titanic,20th Century Fox / Paramount Pictures,$2 263 291 560,$200 000 000,1997,James Cameron
4,Star Wars: Episodio VII - El despertar de la F...,Walt Disney Studios Motion Pictures,$2 071 310 218,$306 000 000,2015,J. J. Abrams
...,...,...,...,...,...,...
95,Shrek The Third,Paramount Pictures,$813 367 380,$160 000 000,2007,Chris Miller
96,Coco,Walt Disney Studios Motion Pictures,$807 817 888,$175 000 000,2017,Lee Unkrich/ Adrian Molina
97,Jumanji: The Next Level,Sony Pictures Releasing,$801 693 929,$125 000 000,2019,Jake Kasdan
98,Harry Potter y el prisionero de Azkaban,Warner Bros. Pictures,$797 660 766,$130 000 000,2004,Alfonso Cuarón
99,Piratas del Caribe: La venganza de Salazar,Walt Disney Studios Motion Pictures,$795 922 298,$230 000 000,2017,Joachim Ronning / Espen Sandberg

In [16]:
#Reemplazo el nombre de la Recaudación mundial por "taquilla_total" para mayor rapidez al configurarlo
pelTaquilla.rename(columns = {'Recaudaciónmundial':'taquilla_total'}, inplace = True)

In [17]:
#Reemplazo el nombre del año de estreno por "año_estreno" para mayor rapidez al configurarlo
pelTaquilla.rename(columns = {'Añodeestreno':'año_estreno'}, inplace = True)

In [18]:
#Reemplazo el nombre de Distribuidora(s) por "emp_distri" para mayor rapidez al configurarlo
pelTaquilla.rename(columns = {'Distribuidora(s)':'emp_distri'}, inplace = True)

In [19]:
#Reemplazo el nombre de Película por "pelicula" para mayor rapidez al configurarlo
pelTaquilla.rename(columns = {'Película':'pelicula'}, inplace = True)

In [20]:
#Reemplazo el nombre de Presupuesto por "presupuesto" para mayor rapidez al configurarlo
pelTaquilla.rename(columns = {'Presupuesto':'presupuesto'}, inplace = True)

In [21]:
#Reemplazo el nombre de Director(es) por "direccion" para mayor rapidez al configurarlo
pelTaquilla.rename(columns = {'Director(es)':'direccion'}, inplace = True)
#Ahora
pelTaquilla

,pelicula,emp_distri,taquilla_total,presupuesto,año_estreno,direccion
0,Avatar,20th Century Fox,$2 923 706 026,$237 000 000,2009,James Cameron
1,Avengers: Endgame,Walt Disney Studios Motion Pictures,$2 799 439 100,$356 000 000,2019,Anthony y Joe Russo
2,Avatar: The Way of Water,Walt Disney Studios Motion Pictures,$2 316 962 130,$350 000 000-460 000 000,2022,James Cameron
3,Titanic,20th Century Fox / Paramount Pictures,$2 263 291 560,$200 000 000,1997,James Cameron
4,Star Wars: Episodio VII - El despertar de la F...,Walt Disney Studios Motion Pictures,$2 071 310 218,$306 000 000,2015,J. J. Abrams
...,...,...,...,...,...,...
95,Shrek The Third,Paramount Pictures,$813 367 380,$160 000 000,2007,Chris Miller
96,Coco,Walt Disney Studios Motion Pictures,$807 817 888,$175 000 000,2017,Lee Unkrich/ Adrian Molina
97,Jumanji: The Next Level,Sony Pictures Releasing,$801 693 929,$125 000 000,2019,Jake Kasdan
98,Harry Potter y el prisionero de Azkaban,Warner Bros. Pictures,$797 660 766,$130 000 000,2004,Alfonso Cuarón
99,Piratas del Caribe: La venganza de Salazar,Walt Disney Studios Motion Pictures,$795 922 298,$230 000 000,2017,Joachim Ronning / Espen Sandberg

In [22]:
#Identificando la celda que tiene un carácter no numérico 
pelTaquilla.taquilla_total.str.contains(pat=r'\D',
                          regex=True)

0     True
1     True
2     True
3     True
4     True
      ...
95    True
96    True
97    True
98    True
99    True
Name: taquilla_total, Length: 100, dtype: bool

In [23]:
#Separando en dos columunas para eliminar el signo de dolar y solo quedarnos con los números en la columna "taquilla_total"
pelTaquilla[['colBorrador1','taquilla_total']]=pelTaquilla.taquilla_total.str.split('$',expand=True)
pelTaquilla

,pelicula,emp_distri,taquilla_total,presupuesto,año_estreno,direccion,colBorrador1
0,Avatar,20th Century Fox,2 923 706 026,$237 000 000,2009,James Cameron,
1,Avengers: Endgame,Walt Disney Studios Motion Pictures,2 799 439 100,$356 000 000,2019,Anthony y Joe Russo,
2,Avatar: The Way of Water,Walt Disney Studios Motion Pictures,2 316 962 130,$350 000 000-460 000 000,2022,James Cameron,
3,Titanic,20th Century Fox / Paramount Pictures,2 263 291 560,$200 000 000,1997,James Cameron,
4,Star Wars: Episodio VII - El despertar de la F...,Walt Disney Studios Motion Pictures,2 071 310 218,$306 000 000,2015,J. J. Abrams,
...,...,...,...,...,...,...,...
95,Shrek The Third,Paramount Pictures,813 367 380,$160 000 000,2007,Chris Miller,
96,Coco,Walt Disney Studios Motion Pictures,807 817 888,$175 000 000,2017,Lee Unkrich/ Adrian Molina,
97,Jumanji: The Next Level,Sony Pictures Releasing,801 693 929,$125 000 000,2019,Jake Kasdan,
98,Harry Potter y el prisionero de Azkaban,Warner Bros. Pictures,797 660 766,$130 000 000,2004,Alfonso Cuarón,
99,Piratas del Caribe: La venganza de Salazar,Walt Disney Studios Motion Pictures,795 922 298,$230 000 000,2017,Joachim Ronning / Espen Sandberg,

In [24]:
#Elimino colBorrador1 usando "drop"
byeColumns=['colBorrador1']

#El resultado
pelTaquilla.drop(columns=byeColumns,inplace=True)
#Ahora
pelTaquilla

,pelicula,emp_distri,taquilla_total,presupuesto,año_estreno,direccion
0,Avatar,20th Century Fox,2 923 706 026,$237 000 000,2009,James Cameron
1,Avengers: Endgame,Walt Disney Studios Motion Pictures,2 799 439 100,$356 000 000,2019,Anthony y Joe Russo
2,Avatar: The Way of Water,Walt Disney Studios Motion Pictures,2 316 962 130,$350 000 000-460 000 000,2022,James Cameron
3,Titanic,20th Century Fox / Paramount Pictures,2 263 291 560,$200 000 000,1997,James Cameron
4,Star Wars: Episodio VII - El despertar de la F...,Walt Disney Studios Motion Pictures,2 071 310 218,$306 000 000,2015,J. J. Abrams
...,...,...,...,...,...,...
95,Shrek The Third,Paramount Pictures,813 367 380,$160 000 000,2007,Chris Miller
96,Coco,Walt Disney Studios Motion Pictures,807 817 888,$175 000 000,2017,Lee Unkrich/ Adrian Molina
97,Jumanji: The Next Level,Sony Pictures Releasing,801 693 929,$125 000 000,2019,Jake Kasdan
98,Harry Potter y el prisionero de Azkaban,Warner Bros. Pictures,797 660 766,$130 000 000,2004,Alfonso Cuarón
99,Piratas del Caribe: La venganza de Salazar,Walt Disney Studios Motion Pictures,795 922 298,$230 000 000,2017,Joachim Ronning / Espen Sandberg

In [25]:
#Eliminando espacios en la columna "taquilla_total"
pelTaquilla.taquilla_total = pelTaquilla.taquilla_total.str.replace(' ', '')
pelTaquilla

,pelicula,emp_distri,taquilla_total,presupuesto,año_estreno,direccion
0,Avatar,20th Century Fox,2923706026,$237 000 000,2009,James Cameron
1,Avengers: Endgame,Walt Disney Studios Motion Pictures,2799439100,$356 000 000,2019,Anthony y Joe Russo
2,Avatar: The Way of Water,Walt Disney Studios Motion Pictures,2316962130,$350 000 000-460 000 000,2022,James Cameron
3,Titanic,20th Century Fox / Paramount Pictures,2263291560,$200 000 000,1997,James Cameron
4,Star Wars: Episodio VII - El despertar de la F...,Walt Disney Studios Motion Pictures,2071310218,$306 000 000,2015,J. J. Abrams
...,...,...,...,...,...,...
95,Shrek The Third,Paramount Pictures,813367380,$160 000 000,2007,Chris Miller
96,Coco,Walt Disney Studios Motion Pictures,807817888,$175 000 000,2017,Lee Unkrich/ Adrian Molina
97,Jumanji: The Next Level,Sony Pictures Releasing,801693929,$125 000 000,2019,Jake Kasdan
98,Harry Potter y el prisionero de Azkaban,Warner Bros. Pictures,797660766,$130 000 000,2004,Alfonso Cuarón
99,Piratas del Caribe: La venganza de Salazar,Walt Disney Studios Motion Pictures,795922298,$230 000 000,2017,Joachim Ronning / Espen Sandberg

In [26]:
#Comprobando si cumple lo solicitado anteriormente en número aleatorios
pelTaquilla.taquilla_total[5:20]

5        2052415039
6        1921847111
7        1671537444
8        1663075401
9        1520538536
10    1 516 341 399
11       1493491858
12       1450683476
13       1402018048
14       1346926083
15       1342359942
16       1334407706
17    1 310 466 296
18       1288540518
19       1264115964
Name: taquilla_total, dtype: object

In [27]:
pelTaquilla.taquilla_total[17]

'1\xa0310\xa0466\xa0296'

In [28]:
pelTaquilla.taquilla_total = pelTaquilla.taquilla_total.str.replace('\xa0', '')

In [29]:
#Identificando la celda que tiene un carácter no numérico 
pelTaquilla.presupuesto.str.contains(pat=r'\D',
                          regex=True)

0     True
1     True
2     True
3     True
4     True
      ...
95    True
96    True
97    True
98    True
99    True
Name: presupuesto, Length: 100, dtype: bool

In [30]:
#Separando en dos columunas para eliminar el signo de dolar y solo quedarnos con los números en la columna "taquilla_total"
pelTaquilla[['colBorrador2','presupuesto']]=pelTaquilla.presupuesto.str.split('$',expand=True)
pelTaquilla

,pelicula,emp_distri,taquilla_total,presupuesto,año_estreno,direccion,colBorrador2
0,Avatar,20th Century Fox,2923706026,237 000 000,2009,James Cameron,
1,Avengers: Endgame,Walt Disney Studios Motion Pictures,2799439100,356 000 000,2019,Anthony y Joe Russo,
2,Avatar: The Way of Water,Walt Disney Studios Motion Pictures,2316962130,350 000 000-460 000 000,2022,James Cameron,
3,Titanic,20th Century Fox / Paramount Pictures,2263291560,200 000 000,1997,James Cameron,
4,Star Wars: Episodio VII - El despertar de la F...,Walt Disney Studios Motion Pictures,2071310218,306 000 000,2015,J. J. Abrams,
...,...,...,...,...,...,...,...
95,Shrek The Third,Paramount Pictures,813367380,160 000 000,2007,Chris Miller,
96,Coco,Walt Disney Studios Motion Pictures,807817888,175 000 000,2017,Lee Unkrich/ Adrian Molina,
97,Jumanji: The Next Level,Sony Pictures Releasing,801693929,125 000 000,2019,Jake Kasdan,
98,Harry Potter y el prisionero de Azkaban,Warner Bros. Pictures,797660766,130 000 000,2004,Alfonso Cuarón,
99,Piratas del Caribe: La venganza de Salazar,Walt Disney Studios Motion Pictures,795922298,230 000 000,2017,Joachim Ronning / Espen Sandberg,

In [31]:
#Identificando la celda que tiene símbolos
pelTaquilla.presupuesto[~pelTaquilla.presupuesto.str.contains(pat=r'[^\w\s]',regex=True)]

0     237 000 000
1     356 000 000
3     200 000 000
4     306 000 000
5     356 000 000
         ...
95    160 000 000
96    175 000 000
97    125 000 000
98    130 000 000
99    230 000 000
Name: presupuesto, Length: 98, dtype: object

In [32]:
#Eliminando espacios en la columna "taquilla_total"
pelTaquilla.presupuesto = pelTaquilla.presupuesto.str.replace(' ', '')
pelTaquilla

,pelicula,emp_distri,taquilla_total,presupuesto,año_estreno,direccion,colBorrador2
0,Avatar,20th Century Fox,2923706026,237000000,2009,James Cameron,
1,Avengers: Endgame,Walt Disney Studios Motion Pictures,2799439100,356000000,2019,Anthony y Joe Russo,
2,Avatar: The Way of Water,Walt Disney Studios Motion Pictures,2316962130,350000000-460000000,2022,James Cameron,
3,Titanic,20th Century Fox / Paramount Pictures,2263291560,200000000,1997,James Cameron,
4,Star Wars: Episodio VII - El despertar de la F...,Walt Disney Studios Motion Pictures,2071310218,306000000,2015,J. J. Abrams,
...,...,...,...,...,...,...,...
95,Shrek The Third,Paramount Pictures,813367380,160000000,2007,Chris Miller,
96,Coco,Walt Disney Studios Motion Pictures,807817888,175000000,2017,Lee Unkrich/ Adrian Molina,
97,Jumanji: The Next Level,Sony Pictures Releasing,801693929,125000000,2019,Jake Kasdan,
98,Harry Potter y el prisionero de Azkaban,Warner Bros. Pictures,797660766,130000000,2004,Alfonso Cuarón,
99,Piratas del Caribe: La venganza de Salazar,Walt Disney Studios Motion Pictures,795922298,230000000,2017,Joachim Ronning / Espen Sandberg,

In [33]:
#Elimino colBorrador2 usando "drop"
byeColumns=['colBorrador2']

#El resultado
pelTaquilla.drop(columns=byeColumns,inplace=True)
#Ahora
pelTaquilla

,pelicula,emp_distri,taquilla_total,presupuesto,año_estreno,direccion
0,Avatar,20th Century Fox,2923706026,237000000,2009,James Cameron
1,Avengers: Endgame,Walt Disney Studios Motion Pictures,2799439100,356000000,2019,Anthony y Joe Russo
2,Avatar: The Way of Water,Walt Disney Studios Motion Pictures,2316962130,350000000-460000000,2022,James Cameron
3,Titanic,20th Century Fox / Paramount Pictures,2263291560,200000000,1997,James Cameron
4,Star Wars: Episodio VII - El despertar de la F...,Walt Disney Studios Motion Pictures,2071310218,306000000,2015,J. J. Abrams
...,...,...,...,...,...,...
95,Shrek The Third,Paramount Pictures,813367380,160000000,2007,Chris Miller
96,Coco,Walt Disney Studios Motion Pictures,807817888,175000000,2017,Lee Unkrich/ Adrian Molina
97,Jumanji: The Next Level,Sony Pictures Releasing,801693929,125000000,2019,Jake Kasdan
98,Harry Potter y el prisionero de Azkaban,Warner Bros. Pictures,797660766,130000000,2004,Alfonso Cuarón
99,Piratas del Caribe: La venganza de Salazar,Walt Disney Studios Motion Pictures,795922298,230000000,2017,Joachim Ronning / Espen Sandberg

In [34]:
#Identificando la celda que aún tiene símbolos, modo de verificación
pelTaquilla.presupuesto[pelTaquilla.presupuesto.str.contains(pat=r'[^\w\s]',regex=True)]

2     350000000-460000000
71    258000000-310000000
Name: presupuesto, dtype: object

In [35]:
#Como vimos anteriormente, solo hay dos celdas que tiene símbolos: la fila 2 y 71 de la columuna presupuesto
#Como estas celdas representan un rango de valores, calculamos el promedio y lo reemplazos
pelTaquilla.loc[2,'presupuesto']='405000000'
pelTaquilla.loc[71,'presupuesto']='284000000'
pelTaquilla

,pelicula,emp_distri,taquilla_total,presupuesto,año_estreno,direccion
0,Avatar,20th Century Fox,2923706026,237000000,2009,James Cameron
1,Avengers: Endgame,Walt Disney Studios Motion Pictures,2799439100,356000000,2019,Anthony y Joe Russo
2,Avatar: The Way of Water,Walt Disney Studios Motion Pictures,2316962130,405000000,2022,James Cameron
3,Titanic,20th Century Fox / Paramount Pictures,2263291560,200000000,1997,James Cameron
4,Star Wars: Episodio VII - El despertar de la F...,Walt Disney Studios Motion Pictures,2071310218,306000000,2015,J. J. Abrams
...,...,...,...,...,...,...
95,Shrek The Third,Paramount Pictures,813367380,160000000,2007,Chris Miller
96,Coco,Walt Disney Studios Motion Pictures,807817888,175000000,2017,Lee Unkrich/ Adrian Molina
97,Jumanji: The Next Level,Sony Pictures Releasing,801693929,125000000,2019,Jake Kasdan
98,Harry Potter y el prisionero de Azkaban,Warner Bros. Pictures,797660766,130000000,2004,Alfonso Cuarón
99,Piratas del Caribe: La venganza de Salazar,Walt Disney Studios Motion Pictures,795922298,230000000,2017,Joachim Ronning / Espen Sandberg

In [36]:
#Identificando la celda que aún tiene símbolos, modo de verificación
pelTaquilla.presupuesto[pelTaquilla.presupuesto.str.contains(pat=r'[^\w\s]',regex=True)]

Series([], Name: presupuesto, dtype: object)

In [37]:
#Comprobando si cumple lo solicitado anteriormente (no espacios) en número aleatorios
pelTaquilla.presupuesto[5:22]

5       356000000
6       200000000
7       150000000
8       260000000
9       220000000
10    190 000 000
11      170000000
12    150 000 000
13      250000000
14    200 000 000
15    250 000 000
16    317 000 000
17    170 000 000
18    150 000 000
19    160 000 000
20    200 000 000
21    250 000 000
Name: presupuesto, dtype: object

In [38]:
pelTaquilla.presupuesto[16]

'317\xa0000\xa0000'

In [39]:
pelTaquilla.presupuesto = pelTaquilla.presupuesto.str.replace('\xa0', '')

In [40]:
#Ahora limpiaremos las columnas con objetos
#Para ello, es necesario identificar que columna presenta un símbolo diferente a una letra o número 
pelTaquilla.emp_distri[pelTaquilla.emp_distri.str.contains(pat=r'[^\w\s]',regex=True)]

3     20th Century Fox / Paramount Pictures
15                    Warner Bros. Pictures
25                    Warner Bros. Pictures
33                    Warner Bros. Pictures
35                    Warner Bros. Pictures
47                    Warner Bros. Pictures
49                    Warner Bros. Pictures
50                    Warner Bros. Pictures
53                    Warner Bros. Pictures
56                    Warner Bros. Pictures
58                    Warner Bros. Pictures
61                    Warner Bros. Pictures
64                    Warner Bros. Pictures
70                    Warner Bros. Pictures
75                    Warner Bros. Pictures
78                    Warner Bros. Pictures
87                    Warner Bros. Pictures
90                    Warner Bros. Pictures
91      Beijing Jingxi Culture & Tourism Co
94                    Warner Bros. Pictures
98                    Warner Bros. Pictures
Name: emp_distri, dtype: object

In [41]:
#Cambiamos "/" por "y"
pelTaquilla.emp_distri = pelTaquilla.emp_distri.str.replace('/', 'y')

In [42]:
#Cambiaremos el nombre de una celda 
pelTaquilla.loc[91,'emp_distri']='Beijing Jingxi Culture y Tourism Co'

In [43]:
#Ahora tenemos:
pelTaquilla.emp_distri[pelTaquilla.emp_distri.str.contains(pat=r'[^\w\s]',regex=True)]

15    Warner Bros. Pictures
25    Warner Bros. Pictures
33    Warner Bros. Pictures
35    Warner Bros. Pictures
47    Warner Bros. Pictures
49    Warner Bros. Pictures
50    Warner Bros. Pictures
53    Warner Bros. Pictures
56    Warner Bros. Pictures
58    Warner Bros. Pictures
61    Warner Bros. Pictures
64    Warner Bros. Pictures
70    Warner Bros. Pictures
75    Warner Bros. Pictures
78    Warner Bros. Pictures
87    Warner Bros. Pictures
90    Warner Bros. Pictures
94    Warner Bros. Pictures
98    Warner Bros. Pictures
Name: emp_distri, dtype: object

In [44]:
pelTaquilla.emp_distri = pelTaquilla.emp_distri.str.replace('.','')

C:\Users\lizbe\AppData\Local\Temp\ipykernel_4280\1793034635.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  pelTaquilla.emp_distri = pelTaquilla.emp_distri.str.replace('.','')

In [45]:
#Ahora tenemos
pelTaquilla

,pelicula,emp_distri,taquilla_total,presupuesto,año_estreno,direccion
0,Avatar,20th Century Fox,2923706026,237000000,2009,James Cameron
1,Avengers: Endgame,Walt Disney Studios Motion Pictures,2799439100,356000000,2019,Anthony y Joe Russo
2,Avatar: The Way of Water,Walt Disney Studios Motion Pictures,2316962130,405000000,2022,James Cameron
3,Titanic,20th Century Fox y Paramount Pictures,2263291560,200000000,1997,James Cameron
4,Star Wars: Episodio VII - El despertar de la F...,Walt Disney Studios Motion Pictures,2071310218,306000000,2015,J. J. Abrams
...,...,...,...,...,...,...
95,Shrek The Third,Paramount Pictures,813367380,160000000,2007,Chris Miller
96,Coco,Walt Disney Studios Motion Pictures,807817888,175000000,2017,Lee Unkrich/ Adrian Molina
97,Jumanji: The Next Level,Sony Pictures Releasing,801693929,125000000,2019,Jake Kasdan
98,Harry Potter y el prisionero de Azkaban,Warner Bros Pictures,797660766,130000000,2004,Alfonso Cuarón
99,Piratas del Caribe: La venganza de Salazar,Walt Disney Studios Motion Pictures,795922298,230000000,2017,Joachim Ronning / Espen Sandberg

In [46]:
#Analizando si la columna "pelicula" contiene simbolos para ser limpiados
pelTaquilla.pelicula[pelTaquilla.pelicula.str.contains(pat=r'[^\w\s]',regex=True)]

1                                     Avengers: Endgame
2                              Avatar: The Way of Water
4     Star Wars: Episodio VII - El despertar de la F...
5                                Avengers: Infinity War
6                               Spider-Man: No Way Home
11                                    Top Gun: Maverick
13                              Avengers: Age of Ultron
15    Harry Potter y las reliquias de la muerte: par...
16          Star Wars: Episodio VIII - Los últimos Jedi
17                       Jurassic World: El reino caído
24                           Capitán América: Civil War
26          El Señor de los Anillos: el retorno del Rey
28                            Spider-Man: Far From Home
30              Transformers: el lado oscuro de la luna
32                 Transformers: la era de la extinción
34     Star Wars: Episodio IX - El ascenso de Skywalker
38           Pirates of the Caribbean: Dead Man's Chest
40                 Rogue One: una historia de Star Wars
42          Pirates of the Caribbean: On Stranger Tides
45          Star Wars: Episodio I - La amenaza fantasma
49                       El hobbit: un viaje inesperado
51                             Jurassic World: Dominion
52                       Jumanji: Welcome to the Jungle
53    Harry Potter y las reliquias de la muerte: par...
56         El hobbit: la batalla de los Cinco Ejércitos
57              Piratas del Caribe: en el fin del mundo
58                    El hobbit: la desolación de Smaug
60              El Señor de los Anillos: las dos torres
63                             Minions: The Rise of Gru
66                          The Super Mario Bros. Movie
69     El Señor de los Anillos: la Comunidad del Anillo
71                                         Spider-Man 3
72                     Ice Age 3: Dawn of the Dinosaurs
74                               Spider-Man: Homecoming
76                         Ice Age 4: Continental Drift
78                   Batman v Superman: Dawn of Justice
80    Star Wars: Episodio lll - La venganza de los Sith
81                     Los juegos del hambre: en llamas
82                      Guardianes de la Galaxia vol. 2
84                       Black Panther: Wakanda Forever
86                                       Thor: Ragnarok
88              Transformers: la venganza de los caídos
89                 La saga Crepúsculo: Amanecer Parte 2
91                                              Hi, Mom
92                                           Spider-Man
97                              Jumanji: The Next Level
99           Piratas del Caribe: La venganza de Salazar
Name: pelicula, dtype: object

In [47]:
#Reemplazamos ":" 
pelTaquilla.pelicula = pelTaquilla.pelicula.str.replace(':', '')

In [48]:
#Ahora tenemos 
pelTaquilla.pelicula[pelTaquilla.pelicula.str.contains(pat=r'[^\w\s]',regex=True)]

4     Star Wars Episodio VII - El despertar de la Fu...
6                                Spider-Man No Way Home
16           Star Wars Episodio VIII - Los últimos Jedi
28                             Spider-Man Far From Home
34      Star Wars Episodio IX - El ascenso de Skywalker
38            Pirates of the Caribbean Dead Man's Chest
45           Star Wars Episodio I - La amenaza fantasma
66                          The Super Mario Bros. Movie
71                                         Spider-Man 3
74                                Spider-Man Homecoming
80     Star Wars Episodio lll - La venganza de los Sith
82                      Guardianes de la Galaxia vol. 2
91                                              Hi, Mom
92                                           Spider-Man
Name: pelicula, dtype: object

In [49]:
#Reemplazamos ":"
pelTaquilla.pelicula = pelTaquilla.pelicula.str.replace('-', '')

In [50]:
#Ahora tenemos 
pelTaquilla.pelicula[pelTaquilla.pelicula.str.contains(pat=r'[^\w\s]',regex=True)]

38    Pirates of the Caribbean Dead Man's Chest
66                  The Super Mario Bros. Movie
82              Guardianes de la Galaxia vol. 2
91                                      Hi, Mom
Name: pelicula, dtype: object

In [51]:
#Reemplazamos el "."
pelTaquilla.pelicula = pelTaquilla.pelicula.str.replace('.', '')

C:\Users\lizbe\AppData\Local\Temp\ipykernel_4280\2271204892.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  pelTaquilla.pelicula = pelTaquilla.pelicula.str.replace('.', '')

In [52]:
#Cambiamos el nombre de la celda en la fila 38 y columna "pelicula" por su nombre en español
pelTaquilla.loc[38,'pelicula']='Piratas del Caribe El cofre de la muerte'

In [53]:
#Cambiamos el nombre de la celda en la fila 91 y columna "pelicula" por su nombre sin coma
pelTaquilla.loc[91,'pelicula']='Hi Mom'

In [54]:
#Ahora tenemos 
pelTaquilla

,pelicula,emp_distri,taquilla_total,presupuesto,año_estreno,direccion
0,Avatar,20th Century Fox,2923706026,237000000,2009,James Cameron
1,Avengers Endgame,Walt Disney Studios Motion Pictures,2799439100,356000000,2019,Anthony y Joe Russo
2,Avatar The Way of Water,Walt Disney Studios Motion Pictures,2316962130,405000000,2022,James Cameron
3,Titanic,20th Century Fox y Paramount Pictures,2263291560,200000000,1997,James Cameron
4,Star Wars Episodio VII El despertar de la Fuerza,Walt Disney Studios Motion Pictures,2071310218,306000000,2015,J. J. Abrams
...,...,...,...,...,...,...
95,Shrek The Third,Paramount Pictures,813367380,160000000,2007,Chris Miller
96,Coco,Walt Disney Studios Motion Pictures,807817888,175000000,2017,Lee Unkrich/ Adrian Molina
97,Jumanji The Next Level,Sony Pictures Releasing,801693929,125000000,2019,Jake Kasdan
98,Harry Potter y el prisionero de Azkaban,Warner Bros Pictures,797660766,130000000,2004,Alfonso Cuarón
99,Piratas del Caribe La venganza de Salazar,Walt Disney Studios Motion Pictures,795922298,230000000,2017,Joachim Ronning / Espen Sandberg

In [55]:
#Comprobación minuciosa de espacios en el caso del guión para la columna "pelicula"
pelTaquilla.pelicula[4]

'Star Wars Episodio VII  El despertar de la Fuerza'

In [56]:
#Se observa doble espacio, por lo tanto, se neceista de un reemplazo
pelTaquilla.pelicula = pelTaquilla.pelicula.str.replace('  ', ' ')

In [57]:
#Comprobación minuciosa de espacios en el caso del guión para la columna "pelicula"
pelTaquilla.pelicula[4]

'Star Wars Episodio VII El despertar de la Fuerza'

In [58]:
#Analizando si la columna "direccion" contiene simbolos para ser limpiados
pelTaquilla.direccion[pelTaquilla.direccion.str.contains(pat=r'[^\w\s]',regex=True)]

4                                    J. J. Abrams
12                       Chris Buck, Jennifer Lee
18                       Chris Buck, Jennifer Lee
21                                   F. Gary Gray
29                         Anna Boden, Ryan Fleck
34                                   J. J. Abrams
43        Pierre Coffin, Kyle Balda, Eric Guillon
44                   Andrew Stanton, Angus McLane
48                       Byron Howard, Rich Moore
62                    Andrew Stanton/ Lee Unkrich
65    Andrew Adamson/ Kelly Asbury/ Conrad Vernon
66                Aaron Horvath / Michael Jelenic
67                  Bryan Singer/ Dexter Fletcher
68                          Chen Kaige/ Tsui Hark
72                Carlos Saldhana/ Mike Thurmeier
76                  Steve Martino/ Mike Thurmeier
83                 Pete Docter/ Ronnie del Carmen
96                     Lee Unkrich/ Adrian Molina
99               Joachim Ronning / Espen Sandberg
Name: direccion, dtype: object

In [59]:
#Al ver la lista de celdas en la columna "direccion" que contienen símbolos, se puede observar que la celda en la fila 43, contiene doble "/", por ello, reemplazamos esta celda manualmente
pelTaquilla.loc[43,'direccion']='Pierre Coffin Kyle Balda y Eric Guillo'
pelTaquilla.direccion[43]

'Pierre Coffin Kyle Balda y Eric Guillo'

In [60]:
#Reemplazando "/" por " y"
pelTaquilla.direccion = pelTaquilla.direccion.str.replace('/', 'y')

In [61]:
#Reemplazando el punto por ''
pelTaquilla.direccion = pelTaquilla.direccion.str.replace('.', '')

C:\Users\lizbe\AppData\Local\Temp\ipykernel_4280\1862232580.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  pelTaquilla.direccion = pelTaquilla.direccion.str.replace('.', '')

In [62]:
#Ahora 
pelTaquilla.direccion[pelTaquilla.direccion.str.contains(pat=r'[^\w\s]',regex=True)]

12        Chris Buck, Jennifer Lee
18        Chris Buck, Jennifer Lee
29          Anna Boden, Ryan Fleck
44    Andrew Stanton, Angus McLane
48        Byron Howard, Rich Moore
Name: direccion, dtype: object

In [63]:
#Reemplazando "," por "y"
pelTaquilla.direccion = pelTaquilla.direccion.str.replace(',', ' y')

In [64]:
#Comprobación minuciosa de espacios en el caso de "/" para la columna "direccion"
pelTaquilla.direccion[95:100]

95                        Chris Miller
96          Lee Unkrichy Adrian Molina
97                         Jake Kasdan
98                      Alfonso Cuarón
99    Joachim Ronning y Espen Sandberg
Name: direccion, dtype: object

In [65]:
#Se observa doble espacio, por lo tanto, se neceista de un reemplazo
pelTaquilla.direccion = pelTaquilla.direccion.str.replace('  ', ' ')

In [66]:
#Ahora 
pelTaquilla.direccion.to_list()

['James Cameron',
 'Anthony y Joe Russo',
 'James Cameron',
 'James Cameron',
 'J J Abrams',
 'Anthony y Joe Russo',
 'Jon Watts',
 'Colin Trevorrow',
 'Jon Favreau',
 'Joss Whedon',
 'James Wan',
 'Joseph Kosinski',
 'Chris Buck y Jennifer Lee',
 'Joss Whedon',
 'Ryan Coogler',
 'David Yates',
 'Rian Johnson',
 'J\xa0A Bayona',
 'Chris Buck y Jennifer Lee',
 'Bill Condon',
 'Brad Bird',
 'F Gary Gray',
 'Shane Black',
 'Pierre Coffin',
 'Anthony y Joe Russo',
 'James Wan',
 'Peter Jackson',
 'Sam Mendes',
 'Jon Watts',
 'Anna Boden y Ryan Fleck',
 'Michael Bay',
 'Steven Spielberg',
 'Michael Bay',
 'Christopher Nolan',
 'J J Abrams',
 'Todd Phillips',
 'Josh Cooley',
 'Lee Unkrich',
 'Gore Verbinski',
 'Rob Minkoff',
 'Gareth Edwards',
 'Guy Ritchie',
 'Rob Marshall',
 'Pierre Coffin Kyle Balda y Eric Guillo',
 'Andrew Stanton y Angus McLane',
 'George Lucas',
 'Tim Burton',
 'Chris Columbus',
 'Byron Howard y Rich Moore',
 'Peter Jackson',
 'Christopher Nolan',
 'Colin Trevorrow',
 'Jake Kasdan',
 'David Yates',
 'Pierre Coffin',
 'Jon Favreau',
 'Peter Jackson',
 'Gore Verbinski',
 'Peter Jackson',
 'Sam Raimi',
 'Peter Jackson',
 'David Yates',
 'Andrew Stantony Lee Unkrich',
 'Pierre Coffin',
 'David Yates',
 'Andrew Adamsony Kelly Asburyy Conrad Vernon',
 'Aaron Horvath y Michael Jelenic',
 'Bryan Singery Dexter Fletcher',
 'Chen Kaigey Tsui Hark',
 'Peter Jackson',
 'Mike Newell',
 'Sam Raimi',
 'Carlos Saldhanay Mike Thurmeier',
 'Sam Mendes',
 'Jon Watts',
 'Chris Columbus',
 'Steve Martinoy Mike Thurmeier',
 'Chris Renaud',
 'Zack Snyder',
 'Wu Jing',
 'George Lucas',
 'Francis Lawrence',
 'James Gunn',
 'Pete Doctery Ronnie del Carmen',
 'Ryan Coogler',
 'Ruben Fleischer',
 'Taika Waititi',
 'Christopher Nolan',
 'Michael Bay',
 'Bill Condon',
 'Patty Jenkins',
 'Ling Jia',
 'Sam Raimi',
 'Roland Emmerich',
 'David Yates',
 'Chris Miller',
 'Lee Unkrichy Adrian Molina',
 'Jake Kasdan',
 'Alfonso Cuarón',
 'Joachim Ronning y Espen Sandberg']

In [67]:
#Analizando celdas de la columna "año_estreno"
pelTaquilla.año_estreno.to_list()

[2009,
 2019,
 2022,
 1997,
 2015,
 2018,
 2021,
 2015,
 2019,
 2012,
 2015,
 2022,
 2019,
 2015,
 2018,
 2011,
 2017,
 2018,
 2013,
 2017,
 2018,
 2017,
 2013,
 2015,
 2016,
 2018,
 2003,
 2012,
 2019,
 2019,
 2011,
 1993,
 2014,
 2012,
 2019,
 2019,
 2019,
 2010,
 2006,
 1994,
 2016,
 2019,
 2011,
 2017,
 2016,
 1999,
 2010,
 2001,
 2016,
 2012,
 2008,
 2022,
 2017,
 2010,
 2013,
 2016,
 2014,
 2007,
 2013,
 2022,
 2002,
 2007,
 2003,
 2022,
 2009,
 2004,
 2023,
 2018,
 2021,
 2001,
 2005,
 2007,
 2009,
 2015,
 2017,
 2002,
 2012,
 2016,
 2016,
 2017,
 2005,
 2013,
 2017,
 2015,
 2022,
 2018,
 2017,
 2010,
 2009,
 2012,
 2017,
 2021,
 2002,
 1996,
 2016,
 2007,
 2017,
 2019,
 2004,
 2017]

In [68]:
#El tipo de información que proporciona la tabla después de la limpieza
pelTaquilla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pelicula        100 non-null    object
 1   emp_distri      100 non-null    object
 2   taquilla_total  100 non-null    object
 3   presupuesto     100 non-null    object
 4   año_estreno     100 non-null    int64
 5   direccion       100 non-null    object
dtypes: int64(1), object(5)
memory usage: 4.8+ KB

In [69]:
#Tabla final
pelTaquilla

,pelicula,emp_distri,taquilla_total,presupuesto,año_estreno,direccion
0,Avatar,20th Century Fox,2923706026,237000000,2009,James Cameron
1,Avengers Endgame,Walt Disney Studios Motion Pictures,2799439100,356000000,2019,Anthony y Joe Russo
2,Avatar The Way of Water,Walt Disney Studios Motion Pictures,2316962130,405000000,2022,James Cameron
3,Titanic,20th Century Fox y Paramount Pictures,2263291560,200000000,1997,James Cameron
4,Star Wars Episodio VII El despertar de la Fuerza,Walt Disney Studios Motion Pictures,2071310218,306000000,2015,J J Abrams
...,...,...,...,...,...,...
95,Shrek The Third,Paramount Pictures,813367380,160000000,2007,Chris Miller
96,Coco,Walt Disney Studios Motion Pictures,807817888,175000000,2017,Lee Unkrichy Adrian Molina
97,Jumanji The Next Level,Sony Pictures Releasing,801693929,125000000,2019,Jake Kasdan
98,Harry Potter y el prisionero de Azkaban,Warner Bros Pictures,797660766,130000000,2004,Alfonso Cuarón
99,Piratas del Caribe La venganza de Salazar,Walt Disney Studios Motion Pictures,795922298,230000000,2017,Joachim Ronning y Espen Sandberg

In [70]:
import os
pelTaquilla.to_csv(os.path.join("CP1","CP1_Badillo-Lizbeth_20212589.csv"),index=False)